/**
 * Punto de entrada de la capa de API.
 *
 * Los componentes importan SIEMPRE de aqui y nunca de `./http` ni de
 * `./contract`. Es lo que permite que, cuando `packages/api-types` exista
 * (DEC-014), la sustitucion sea un cambio en esta carpeta y no una reescritura
 * de la interfaz.
 */

export type {
  AcknowledgedResponse,
  AmoeMode,
  ApiErrorEnvelope,
  Cart,
  CartLine,
  CartWithQuote,
  CheckoutMode,
  CheckoutSessionResponse,
  CheckoutSessionState,
  CheckoutSessionStatus,
  ConsentAcceptance,
  ConsentRequirement,
  CursorPage,
  EntryBatch,
  EntryBatchPage,
  EntryCalculationSnapshot,
  EntryMultiplier,
  EntryOffer,
  EntryPool,
  EntryQuote,
  EntryQuoteAppliedCap,
  EntryQuoteAppliedMultiplier,
  EntryQuoteEligibleItem,
  EntryQuoteIneligibleItem,
  EntrySummary,
  EntryTransaction,
  EntryTransactionPage,
  FeatureFlagKey,
  LocalizedText,
  MoneyMinor,
  OfficialRulesDocumentContent,
  OfficialRulesResponse,
  OrderDetail,
  OrderEntryState,
  OrderLine,
  OrderPage,
  OrderStatus,
  OrderSummary,
  ParticipantProfile,
  PostalAddress,
  ProductDetail,
  ProductEntryEligibility,
  ProductListQuery,
  ProductListResponse,
  ProductSummary,
  ProductVariant,
  PromotionDetail,
  PromotionListResponse,
  PromotionMedia,
  PromotionPrize,
  PromotionStatus,
  LogoutResponse,
  PromotionSummary,
  SessionLifecycle,
  SessionScope,
  SessionState,
  SiteConfigResponse,
  VariantAvailability,
} from "./contract";
export {
  AMOE_MODES,
  CHECKOUT_MODES,
  CHECKOUT_SESSION_STATUSES,
  FEATURE_FLAG_KEYS,
  ORDER_ENTRY_STATES,
  ORDER_STATUSES,
  PROMOTION_LIFECYCLE,
  PROMOTION_STATUSES,
  SESSION_LIFECYCLES,
  SESSION_SCOPES,
  VARIANT_AVAILABILITIES,
} from "./contract";
export { apiBaseUrl } from "./http";
export { isCompleteLocalizedText, pickLocalized } from "./localized";
export {
  addCartItem,
  ANONYMOUS_SESSION,
  API_PATHS,
  cartItemPath,
  checkoutSessionPath,
  createCheckoutSession,
  fetchActivePromotion,
  fetchCart,
  fetchCartEntryQuote,
  fetchCheckoutSession,
  fetchEntryBatches,
  fetchEntrySummary,
  fetchEntryTransactions,
  fetchMe,
  fetchOfficialRules,
  fetchOrder,
  fetchOrders,
  fetchProduct,
  fetchProducts,
  fetchPromotion,
  fetchPromotions,
  fetchSession,
  fetchSiteConfig,
  login,
  logout,
  officialRulesPath,
  orderPath,
  productPath,
  promotionPath,
  register,
  removeCartItem,
  requestPasswordReset,
  resendEmailVerification,
  resetPassword,
  updateCartItem,
  updateMe,
  verifyEmail,
  verifyMfa,
  type SessionContext,
} from "./resources";
export type { ApiFailure, ApiFailureKind, ApiResult } from "./result";
